{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.15.jar",
          "url": "spring-boot-starter-2.6.15.jar",
          "size": 4772,
          "sha512": "d1acee1a42850501b5944e484ca89c9f4ddf8a69d7373ccf68ef365f4ac7eda07accca85438903192b8fde0be98ee8efcb3121ec0b529d72703de30d73ffa41c",
          "sha256": "d79a6c175c8b2d50a18d65cce40010a7ba064b90e7d269469267a7c89020630f",
          "sha1": "d627ef1cf290b670d46dc5b78b8950761d03e43c",
          "md5": "174003acb6db006c91d420ed6c252c65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.15.jar",
          "url": "spring-boot-starter-2.6.15.jar",
          "size": 4772,
          "sha512": "d1acee1a42850501b5944e484ca89c9f4ddf8a69d7373ccf68ef365f4ac7eda07accca85438903192b8fde0be98ee8efcb3121ec0b529d72703de30d73ffa41c",
          "sha256": "d79a6c175c8b2d50a18d65cce40010a7ba064b90e7d269469267a7c89020630f",
          "sha1": "d627ef1cf290b670d46dc5b78b8950761d03e43c",
          "md5": "174003acb6db006c91d420ed6c252c65"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.15.jar",
          "url": "spring-boot-starter-2.6.15.jar",
          "size": 4772,
          "sha512": "d1acee1a42850501b5944e484ca89c9f4ddf8a69d7373ccf68ef365f4ac7eda07accca85438903192b8fde0be98ee8efcb3121ec0b529d72703de30d73ffa41c",
          "sha256": "d79a6c175c8b2d50a18d65cce40010a7ba064b90e7d269469267a7c89020630f",
          "sha1": "d627ef1cf290b670d46dc5b78b8950761d03e43c",
          "md5": "174003acb6db006c91d420ed6c252c65"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.15.jar",
          "url": "spring-boot-starter-2.6.15.jar",
          "size": 4772,
          "sha512": "d1acee1a42850501b5944e484ca89c9f4ddf8a69d7373ccf68ef365f4ac7eda07accca85438903192b8fde0be98ee8efcb3121ec0b529d72703de30d73ffa41c",
          "sha256": "d79a6c175c8b2d50a18d65cce40010a7ba064b90e7d269469267a7c89020630f",
          "sha1": "d627ef1cf290b670d46dc5b78b8950761d03e43c",
          "md5": "174003acb6db006c91d420ed6c252c65"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.15-javadoc.jar",
          "url": "spring-boot-starter-2.6.15-javadoc.jar",
          "size": 4740,
          "sha512": "7d44de068196c8752b4c252eb4346f02e151ecb2a3cf923500daf5d585c9b764db9da1dab26dd03a7d98aaf37a2d0992c592d53df702dfa8afc1ee83aa5ff1ff",
          "sha256": "a8a57cb174843d6e18eb408a4f10ef47d1c585cad5289e113cef0a1f18e8328e",
          "sha1": "edf7bfd09f0dbe9b89f56acedb302b4b2892ca4c",
          "md5": "ebd80251da7d01d289620894301298e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.15-sources.jar",
          "url": "spring-boot-starter-2.6.15-sources.jar",
          "size": 4738,
          "sha512": "1f0611218f39b1f061307dc24c76a0e63526a266bfeb26c5fc340ee1f1b61b96484508420790356df72a36eab372163bc688222c44a9061fa5e3b33f659567aa",
          "sha256": "75e8bef43d0e48422dce8044348212ce190b461421bb24c6efa173cff0144497",
          "sha1": "c002ffeddd50a3e7bed21a0c1e48cd974d7d003a",
          "md5": "cf8647636b0075456988e89f0ae4c820"
        }
      ]
    }
  ]
}
