{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "5.3.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-5.3.27.jar",
          "url": "spring-aop-5.3.27.jar",
          "size": 383434,
          "sha512": "7b273131eade41c889134033f72a322f3ec647e2cbf592536bfdfbd1c1a83ff6bb21341173f89598576b99eaca3d56aa10bbff210bfd09fb962e2b4cb9f95a0a",
          "sha256": "3c4ea9f2074686efda6ec84e63433a3c6b9e1d795fa3442854e6b1445e141607",
          "sha1": "ecae2962d53c587fd0e405cd60dc8415d1b9e12d",
          "md5": "b56118bf0c21c608bc04a0ae9c6f5f1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-5.3.27.jar",
          "url": "spring-aop-5.3.27.jar",
          "size": 383434,
          "sha512": "7b273131eade41c889134033f72a322f3ec647e2cbf592536bfdfbd1c1a83ff6bb21341173f89598576b99eaca3d56aa10bbff210bfd09fb962e2b4cb9f95a0a",
          "sha256": "3c4ea9f2074686efda6ec84e63433a3c6b9e1d795fa3442854e6b1445e141607",
          "sha1": "ecae2962d53c587fd0e405cd60dc8415d1b9e12d",
          "md5": "b56118bf0c21c608bc04a0ae9c6f5f1e"
        }
      ]
    }
  ]
}
