{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "5.3.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.27.jar",
          "url": "spring-beans-5.3.27.jar",
          "size": 703417,
          "sha512": "22d63e16c5366926d967fc3e27801bed4951f440608b3e160bba875009219807dba6a578d398d1ad7f31f4071e7f7a15b9e9b88feadd69b23714a5481f5ca669",
          "sha256": "c9a4c967c231addfcbb1cbc098899c5628c5d01c469664f45bea40eeed7d7278",
          "sha1": "46e7d917551ffcc0a104fd971d1fa207b30d7761",
          "md5": "329f32db60cbb2ad16c9695f4a1d13f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.27.jar",
          "url": "spring-beans-5.3.27.jar",
          "size": 703417,
          "sha512": "22d63e16c5366926d967fc3e27801bed4951f440608b3e160bba875009219807dba6a578d398d1ad7f31f4071e7f7a15b9e9b88feadd69b23714a5481f5ca669",
          "sha256": "c9a4c967c231addfcbb1cbc098899c5628c5d01c469664f45bea40eeed7d7278",
          "sha1": "46e7d917551ffcc0a104fd971d1fa207b30d7761",
          "md5": "329f32db60cbb2ad16c9695f4a1d13f1"
        }
      ]
    }
  ]
}
