{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.75"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.75"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.75"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15.jar",
          "url": "spring-boot-starter-tomcat-2.6.15.jar",
          "size": 4798,
          "sha512": "619938b4bb4b7f7927b803080e795a04d6c690e0888d0befca2e72f1fdf1c50cd6906eba1eb861c150df8480a4a7afdd7ac4ee1d766b3c52f0f759cf10fc6d26",
          "sha256": "40d2b570b30d56d60fa486eaa142df0abb21d9196fb8966ab088dff307327f72",
          "sha1": "716444ab016660ffc889f4bcb66ec1170fa3aaf5",
          "md5": "f9e1aa58b6b20cf843ae395bb95c8d69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.75"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.75"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.75"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15.jar",
          "url": "spring-boot-starter-tomcat-2.6.15.jar",
          "size": 4798,
          "sha512": "619938b4bb4b7f7927b803080e795a04d6c690e0888d0befca2e72f1fdf1c50cd6906eba1eb861c150df8480a4a7afdd7ac4ee1d766b3c52f0f759cf10fc6d26",
          "sha256": "40d2b570b30d56d60fa486eaa142df0abb21d9196fb8966ab088dff307327f72",
          "sha1": "716444ab016660ffc889f4bcb66ec1170fa3aaf5",
          "md5": "f9e1aa58b6b20cf843ae395bb95c8d69"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15.jar",
          "url": "spring-boot-starter-tomcat-2.6.15.jar",
          "size": 4798,
          "sha512": "619938b4bb4b7f7927b803080e795a04d6c690e0888d0befca2e72f1fdf1c50cd6906eba1eb861c150df8480a4a7afdd7ac4ee1d766b3c52f0f759cf10fc6d26",
          "sha256": "40d2b570b30d56d60fa486eaa142df0abb21d9196fb8966ab088dff307327f72",
          "sha1": "716444ab016660ffc889f4bcb66ec1170fa3aaf5",
          "md5": "f9e1aa58b6b20cf843ae395bb95c8d69"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15.jar",
          "url": "spring-boot-starter-tomcat-2.6.15.jar",
          "size": 4798,
          "sha512": "619938b4bb4b7f7927b803080e795a04d6c690e0888d0befca2e72f1fdf1c50cd6906eba1eb861c150df8480a4a7afdd7ac4ee1d766b3c52f0f759cf10fc6d26",
          "sha256": "40d2b570b30d56d60fa486eaa142df0abb21d9196fb8966ab088dff307327f72",
          "sha1": "716444ab016660ffc889f4bcb66ec1170fa3aaf5",
          "md5": "f9e1aa58b6b20cf843ae395bb95c8d69"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.6.15-javadoc.jar",
          "size": 4746,
          "sha512": "f3e81b8dd43cd48afdd8a955b1f8a359742398e89bfa29bf4e13e126bcc3ec6d9d35074a32cd2b0bfc390e250c8b83b4dc610d4800aa06f8955b6ad5c7f3d490",
          "sha256": "a4302f02d83832184a99afbcd0b609db80bc6ccf931645d9311785e796d7b408",
          "sha1": "7a65b9f89ba616a171c395f2305e1a3eb1032e87",
          "md5": "816e848f7b03fe415696b498f505db45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.15-sources.jar",
          "url": "spring-boot-starter-tomcat-2.6.15-sources.jar",
          "size": 4745,
          "sha512": "77342697600ec02eb62d5cee5769e834f8fc6e7feb9ff54276bed0728a3c8fc2e466f3eeee892ddd872039ef63900d05f6633e402d167c488a13364ce59780c4",
          "sha256": "a8a745479979b5409784d293ba0b9358ddf8d291871ef662a963e02c14535238",
          "sha1": "1a0a8074c9dc075cb6342bfd989cd733cc855bd2",
          "md5": "53560b794cbcbff444ccfbda9ea0e816"
        }
      ]
    }
  ]
}
