{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "5.3.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.29"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webflux-5.3.27.jar",
          "url": "spring-webflux-5.3.27.jar",
          "size": 947189,
          "sha512": "1bf012c08f91a05d2466874068474dc76250e5b3739e010fbc43eca708fd36c9ba2be872fbd1ab7f843643f049337752bb920f8ff4f0ca53b1297892881282e2",
          "sha256": "4033446ad5e643968f1c91339160a847ba830a1aa269c0f89636a69064ab5183",
          "sha1": "596b5de00091555d027e36bee25ba0e2718c7490",
          "md5": "5c41768e59056620a3f20c6196199528"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.29"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-servlet-api"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.jboss.spec.javax.websocket",
              "module": "jboss-websocket-api_1.1_spec"
            },
            {
              "group": "org.jboss.spec.javax.servlet",
              "module": "jboss-servlet-api_4.0_spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.jboss.spec.javax.annotation",
              "module": "jboss-annotations-api_1.3_spec"
            },
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-websocket-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webflux-5.3.27.jar",
          "url": "spring-webflux-5.3.27.jar",
          "size": 947189,
          "sha512": "1bf012c08f91a05d2466874068474dc76250e5b3739e010fbc43eca708fd36c9ba2be872fbd1ab7f843643f049337752bb920f8ff4f0ca53b1297892881282e2",
          "sha256": "4033446ad5e643968f1c91339160a847ba830a1aa269c0f89636a69064ab5183",
          "sha1": "596b5de00091555d027e36bee25ba0e2718c7490",
          "md5": "5c41768e59056620a3f20c6196199528"
        }
      ]
    }
  ]
}
