{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15.jar",
          "size": 4760,
          "sha512": "182df452034e7ca37445c579e9fc0be8eda13f0802cb95713aedb3924a0562a2a4e7499d80d907fa266bd7afbfa08cc59a1428bd3e180f7b1bc0a95246d6f7fb",
          "sha256": "5ce03dc8da57120334635bebcd2169b24e4a630d553ad0faf809699ba623ccbc",
          "sha1": "5b2e313dabe3ecbfaad63120b2155f57f4780ab4",
          "md5": "c78677ccc7ba5670d1aee8c2e81e81fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.15"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15.jar",
          "size": 4760,
          "sha512": "182df452034e7ca37445c579e9fc0be8eda13f0802cb95713aedb3924a0562a2a4e7499d80d907fa266bd7afbfa08cc59a1428bd3e180f7b1bc0a95246d6f7fb",
          "sha256": "5ce03dc8da57120334635bebcd2169b24e4a630d553ad0faf809699ba623ccbc",
          "sha1": "5b2e313dabe3ecbfaad63120b2155f57f4780ab4",
          "md5": "c78677ccc7ba5670d1aee8c2e81e81fb"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15.jar",
          "size": 4760,
          "sha512": "182df452034e7ca37445c579e9fc0be8eda13f0802cb95713aedb3924a0562a2a4e7499d80d907fa266bd7afbfa08cc59a1428bd3e180f7b1bc0a95246d6f7fb",
          "sha256": "5ce03dc8da57120334635bebcd2169b24e4a630d553ad0faf809699ba623ccbc",
          "sha1": "5b2e313dabe3ecbfaad63120b2155f57f4780ab4",
          "md5": "c78677ccc7ba5670d1aee8c2e81e81fb"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15.jar",
          "size": 4760,
          "sha512": "182df452034e7ca37445c579e9fc0be8eda13f0802cb95713aedb3924a0562a2a4e7499d80d907fa266bd7afbfa08cc59a1428bd3e180f7b1bc0a95246d6f7fb",
          "sha256": "5ce03dc8da57120334635bebcd2169b24e4a630d553ad0faf809699ba623ccbc",
          "sha1": "5b2e313dabe3ecbfaad63120b2155f57f4780ab4",
          "md5": "c78677ccc7ba5670d1aee8c2e81e81fb"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.15"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15-javadoc.jar",
          "size": 4751,
          "sha512": "6edf02f6c8d5a78acc4356df57f838e86e2862321179a848e80e8d4e2589f0fbb85a1e21cc875d4576ed027782de28b2dbab96d401b8f0d0be56489a0ef77963",
          "sha256": "dfe57046556a32f02f85d0eb02b7608857b95213ccf049d70891c8a771de86af",
          "sha1": "c58402d4de9140797a305bd4ce90fd05b5fc5c09",
          "md5": "e516339d31c9c1c0463fcf4999489c10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.15-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.6.15-sources.jar",
          "size": 4749,
          "sha512": "3ae5366b49b195c1294a27851b7d93291d3ae16a989a3aa30987fa04114f2751929554bfffc7b77a809fc7cee07cfda6c7551ebfc81131472abe0741e58ae5e4",
          "sha256": "a989b561db2c84966bfbcdebb5c62bf6c75113a2ea8301ebfefe21afce5d5222",
          "sha1": "3ec1af726fb5beeffa3f73dd103af6cae33dcf3c",
          "md5": "9b9b08c59d8aa59d2ff94cf01aec681f"
        }
      ]
    }
  ]
}
